apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: self-node-remediation
  namespace: openshift-workload-availability 
spec:
  channel: stable
  installPlanApproval: Manual
  name: self-node-remediation
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: self-node-remediation.v0.10.2
  