apiVersion: v1
kind: Secret
metadata:
  name: config-bundle-secret
  namespace: {{ default .Release.Namespace .Values.namespace }}
type: Opaque
data:
  config.yaml: {{ tpl .Values.configTemplate . | b64enc | quote }}
