apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: htpass-secret
    mappingMethod: claim
    name: Htpasswd
    type: HTPasswd
  - name: EntraID
    mappingMethod: claim
    type: OpenID
    openID:
      clientID: 5d69f2cc-cd20-4613-a338-bbb745dbda5e
      clientSecret:
        name: secret-entraid
      claims:
        preferredUsername:
        - email
        name:
        - name
        email:
        - email
        groups:
        - groups
      issuer: https://login.microsoftonline.com/f46345aa-4fa0-4d1e-bc2c-aa469179a252/v2.0