apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-secret-writer
  namespace: openshift-config
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-secret-writer-binding
  namespace: openshift-config
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  kind: Role
  name: argocd-secret-writer
  apiGroup: rbac.authorization.k8s.io
