apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: oauth-local-cluster
  name: v4-0-config-user-idp-0-file-data
  namespace: openshift-authentication
type: Opaque
data:
  htpasswd: YWRtaW46JDJ5JDA1JFhVUXV4ZWs5b1JSZ0g5QTJYNXJ0Z2VieHJ0bENFYmNwdk9WaUV4WEVnb095bS93U0VJckR1
